name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@latst
        with:
          server: 'ftpupload.net'  # InfinityFree's FTP server
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: rama.10001mb.com/htdocs/
          debug: true 
