name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_mysql

      - name: Install Dependencies
        run: composer install

      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@latest
        with:
          server: 'ftpupload.net'
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: rama.html-5.me/htdocs/
 debug: true 
